[package]
name = "sql_query_engine"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
sqlparser = { version = "0.5.0", features = ["bigdecimal"] }
bigdecimal = { version = "0.1.2", features = ["serde", "string-only"] }
num-bigint = { version = "0.2.6", features = ["serde"] }
num-traits = "0.2.11"
bincode = "1.2.1"
types = { path = "../types" }
