[package]
name = "client_server"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"

[dependencies]
mio = { version = "0.7", features = ["os-poll", "tcp"] }
pretty_env_logger = "0.4.0"
log = "0.4.8"
bincode = "1.2.1"
sql_query_engine = { path = "../sql_query_engine" }

