[package]
name = "relational_storage"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"

[dependencies]
bigdecimal = { version = "0.1.2", features = ["serde", "string-only"] }
num-bigint = { version = "0.2.6", features = ["serde"] }
num-traits = "0.2.11"
types = { path = "../types" }
